name: Deployment
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install and Build
        run: npm ci && npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4 # deploying to github pages using this
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build # The folder the action should deploy.
